---
- name: subcribe machine and ensure proper repos are attached
  include_tasks: sub_manager.yml
  when: configure_subscription_manager == 'True'

- name: configure docker launch docker registry container pull OCP images from Red Hat push OCP images to docker registry container
  include_tasks: docker_registry_container.yml
  when: configure_deploy_docker_registry == 'True'

- name: archive images to local tarball
  include_tasks: archive_docker_images.yml
  when: archive_docker_images == 'True'

- name: reposync and create offline repos
  include_tasks: repo_create_sync.yml
  when: repo_create_sync == 'True'
